#cloud-config
#set ip on dhcp server based on vm mac address
#key is to debian wsl on lenovo
hostname: rancher

rancher:
  network:
    interfaces:
      eth*:
       dhcp: true
    dns:
     nameservers:
      - 1.1.1.1

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDERnxYZAoZkQmhzpSQnxfgWQ3pbRZ1rlgqwmglOWkXjdw6xfbBuK+DuvKwdECDxLrDTtYTC5q899YZ3fFpWtsSdVCAAlzbJimjDERhOVG1pm2FzPS4hOkw5YVpbNuqrv0OvVoK7w6FgH0dMs9EM0ArSuyYioMjrtzpml/jMz4ApsFnZLe29XaVEmNDo3HCvv8dJfGdtS574xF4NGCAeTOOgP1xMRFOpZnOg3hn0JXnuKZiCpfQU64NNr0lxgNwjbmMhLjklUD2jAQbJ5FoVYIxaRcwWpkvKWfNjST/jRcuntLgNAGgkNsOV0UyJIusrXbxrITZRwp53Z/329XEzcaz jfsanchez@Lenov0910
